routes:
  /tag/:
    template: page-tags
  /new-design/: 
    template: index-new
    

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
